---
title: "My dataset"
author: "Leo Lu"
date: "2024-10-10"
output: "github_document"
---
```{r}
library(haven)
library(psych)
library(dplyr)
library(ggplot2)
library(tidyr)
library(bruceR)
library(ggsci)
library(see)
library(car)
library(ggstatsplot)
library(performance)
library(sjPlot)
library(tidyverse)
library(ggcorrplot)


load("/Users/leolu/Documents/38964-0001-Data.rda")

```

```{r}
mydataset <- da38964.0001 %>%
  select(SAT1, SAT2, SAT3, SAT4, SAT5, EMP_1, EMP_2, HAPPY, SOCIAL_2, AGE, WORK_HRS, SLEEPHRS,)

mydataset$SAT1 <- as.numeric(mydataset$SAT1)

describe(mydataset$SAT1)

mydataset <- mydataset %>%
  filter(SAT1 < 6)

summary(mydataset$SAT1)

mydataset$SAT2 <- as.numeric(mydataset$SAT2)

describe(mydataset$SAT2)

mydataset <- mydataset %>%
  filter(SAT2 < 6)

summary(mydataset$SAT2)

mydataset$SAT3 <- as.numeric(mydataset$SAT3)

describe(mydataset$SAT3)

mydataset <- mydataset %>%
  filter(SAT3 < 6)

summary(mydataset$SAT3)

mydataset$SAT4 <- as.numeric(mydataset$SAT4)

describe(mydataset$SAT4)

mydataset <- mydataset %>%
  filter(SAT4 < 6)

summary(mydataset$SAT4)

mydataset$SAT5 <- as.numeric(mydataset$SAT5)

describe(mydataset$SAT5)

mydataset <- mydataset %>%
  filter(SAT5 < 6)

summary(mydataset$SAT5)

describe(mydataset$SAT5)

mydataset <- mydataset %>%
  mutate(SAT = rowMeans(cbind(SAT1, SAT2, SAT3, SAT4, SAT5)))

mydataset$SOCIAL_2 <- as.numeric(mydataset$SOCIAL_2)

describe(mydataset$SOCIAL_2)

mydataset %>% count(SOCIAL_2)

mydataset$SOCIAL_R <- 5 - mydataset$SOCIAL_2

mydataset %>% count(SOCIAL_R)

summary(mydataset$SOCIAL_R)

describe(mydataset$SOCIAL_R)

mydataset$HAPPY <- as.numeric(mydataset$HAPPY)

describe(mydataset$HAPPY)

mydataset %>% count(HAPPY)

mydataset$HAPPY_R <- 5 - mydataset$HAPPY

mydataset %>% count(HAPPY_R)

summary(mydataset$HAPPY_R)

describe(mydataset$HAPPY_R)



```
```{r}
summary(mydataset)
mydataset %>%
  dplyr::summarize(mean_AGE    = mean(AGE),
      std_dev_AGE = sd(AGE))
```

```{r}

mydataset <- mydataset %>%
  filter(EMP_1 != "(99) Refusal")

mydataset <- mydataset %>%
  mutate_at(c('EMP_1'),funs(str_replace(., "(00) Item not selected", "Not in One Job")))
mydataset <- mydataset %>%  
  mutate_at(c('EMP_1'),funs(str_replace(., "(01) Item selected", "One Job")))

  summary(mydataset$EMP_1)

mydataset <- mydataset %>%
  filter(EMP_2 != "(99) Refusal")

mydataset<- mydataset%>%
  mutate_at(c('EMP_2'),funs(str_replace(., "(00) Item not selected", "Not in Multiple Jobs")))

mydataset<- mydataset%>%
  mutate_at(c('EMP_2'),funs(str_replace(., "(01) Item selected", "Multiple Jobs")))


summary(mydataset$EMP_2)


```

```{r}
mydataset$Employed <- ifelse(mydataset$EMP_1 == "(01) Item selected" | mydataset$EMP_2 == "(01) Item selected", "1", "0")

mydatasetr <- mydataset %>%
  rename(
    SWL = SAT,
    Happiness = HAPPY_R,
    Employment_Status = Employed,
    Social_Interaction = SOCIAL_R,
    Age = AGE
  )

model<-lm(SWL ~ Social_Interaction + Employment_Status + Age, data = mydatasetr)

performance(model)

check_model(model)

model_summary(model, show.std = TRUE)

summary(model)

tab_model(model)

plot_model(model,  type ="std",  show.values = TRUE, vline.color = "#1B191999", line.size = 1, dot.size = 2.5, colors = "black", axis.lim = c(-1, 1)) + theme_bruce() 

ggplot(mydataset, aes(x = SOCIAL_R, Employed, y = SAT)) + geom_point() + geom_smooth(method = lm) + theme_bruce()



#Higher score of social interaction means more Social interaction, Employed yes means employed.
#7.1 % of the variability is explained by the whole model. One unit increase in Social interaction frequency means a 0.197 increase in Satisfaction With life. Being employed means a 0.194 increase in satisfaction with life.
```

```{r}
mydataset$Employed <- ifelse(mydataset$EMP_1 == "(01) Item selected" | mydataset$EMP_2 == "(01) Item selected", "1", "0")

model<-lm(Happiness ~ Social_Interaction + Employment_Status + Age, data = mydatasetr)

performance(model)

check_model(model)

model_summary(model, show.std = TRUE)

summary(model)

tab_model(model)

plot_model(model,  type ="est",  show.values = TRUE, vline.color = "#1B191999", line.size = 1, dot.size = 2, colors = "black") + theme_bruce()

ggplot(mydataset, aes(x = SOCIAL_R, Employed, y = HAPPY_R)) + geom_point() + geom_smooth(method = lm) + theme_bruce()
```

```{r}
corrdataset <- mydatasetr %>%
  select(SWL, Happiness, Employment_Status, Social_Interaction, Age) %>% mutate(Employment_Status = as.numeric(Employment_Status))

Corr(corrdataset, plot.colors=c("#b2182b", "white", "#2166ac"))

corr_matrix <- cor(corrdataset, use = "complete.obs") 

ggcorrplot(corr_matrix, method = "square", colors = c("blue", "grey", "white"), title = "Correlation Plot", lab = TRUE)
```
```{r}

Alpha(mydataset, "SAT", 1:5)

EFA(mydataset, "SAT", 1:5, method = "pa", plot.scree = TRUE, nfactors = c("parallel"))


```





